### ISSUE TITLE
cameraTargetBounds not working on Android

### ISSUE THREAD

**Issue by stefanschaller** [m0nac0/flutter-mapbox-gl#273]
We need to restrict the visible area to a specific country, since we don't want to show the whole world. 

Minimal example to reproduce the issue:

```
MaplibreMap(
        cameraTargetBounds: CameraTargetBounds(
          LatLngBounds(
            northeast: const LatLng(52.278241, 8.289185),
            southwest: const LatLng(48.558432, 1.016235),
          ),
        ),
        initialCameraPosition: const CameraPosition(
          target: LatLng(50.834060793873505, 4.340443996254663),
          zoom: 14,
        ),
      )
```

I'm using the following versions: 
Flutter:`3.10.5` 
MapLibre: `ec9808e22eaca1c21c0728def02a3b3e96e298a5`
```
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl
      ref: main
```

The bounds should constrain the possible viewport on each platform. The example is working on Web, but ignored on Android.
