### ISSUE TITLE
Upgrade Android Gradle Plugin to 8.x.x

### ISSUE THREAD

**Issue by Lee-Yoonjoo** [m0nac0/flutter-mapbox-gl#310]
<img width="734" alt="Screenshot 2023-10-06 at 09 28 47" src="https://github.com/maplibre/flutter-maplibre-gl/assets/26617897/e57f24d5-0355-4241-9d3a-a7a8a4e42e9a">

Hello maintainers,

I am currently using a [forked library](https://github.com/Grodien/flutter-maplibre-gl.git) of this library in my project . I am trying to update my flutter project's Android Gradle Plugin (AGP) to 8.x.x, but I am encountering some compatibility issues.

I'm aware of the option to fork, make corrections, and then use the forked version, but I believe that it might not be the most practical solution for the community.

> My Question:

Do you have any plans in the near future to update this library to be compatible with AGP 8.x.x?

> Environment:

Flutter version: 3.13.5 via FVM
flutter-maplibre-gl version: 

```
  maplibre_gl:
    git:
      url: https://github.com/Grodien/flutter-maplibre-gl.git
      ref: delayedDisposalCrash

```
But eventually I hope that I can overwrite your library.
```
maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
```

Android : 
**android/app/build.gradle**
```
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
   kotlinOptions {
        jvmTarget = '17'
    }
```
**/android/build.gradle**
```
buildscript {
    // ...
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.1'
        // ...
    }
}

```
AGP version: 
**gradle-wrapper.properties**
`distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip`

Thank you for your assistance and for maintaining this library!
